import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const contentDir = path.join(root, 'content');
const publicDir = path.join(root, 'public');
const readJson = (name) => JSON.parse(fs.readFileSync(path.join(contentDir, name), 'utf8'));
const site = readJson('site.json');
const essays = readJson('essays.json');
const principles = readJson('principles.json');
const conversations = readJson('conversations.json');
const dc = readJson('dcdecoded.json');

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
fs.cpSync(publicDir, out, { recursive: true });

const esc = (s='') => String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const prettyDate = (d) => d ? new Intl.DateTimeFormat('en-GB', { day:'numeric', month:'long', year:'numeric' }).format(new Date(`${d}T12:00:00Z`)) : '';
const dateHtml = (e) => `<span>${esc(e.collection || e.source || 'Essay')}</span>`;
const cleanLinkedInHtml = (html='') => {
  let out = html;
  out = out.replace(/<h3>\s*(?:🔖\s*)?Hashtags\s*<\/h3>/gi, '');
  out = out.replace(/<p>[^<]*(?:#(?:[A-Za-z0-9_]+)[^<]*){2,}<\/p>/gi, '');
  out = out.replace(/<p>\s*(?:👉\s*)?<strong>(?:Over to you|Your turn):?<\/strong>[\s\S]*?<\/p>/gi, '');
  out = out.replace(/<h3>\s*(?:Over to you|Your turn)\.?\s*<\/h3>/gi, '');
  out = out.replace(/<p>[\s\S]*?(?:Drop it in the comments|Share it here|This is Episode \d+ of my weekly story series)[\s\S]*?<\/p>/gi, '');
  out = out.replace(/<p>\s*(?:_|⸻|·\s*·\s*·)+\s*<\/p>/gi, '<hr>');
  return out;
};
const articleBody = (e) => cleanLinkedInHtml(e.bodyHtml || (e.body || []).map(p=>`<p>${esc(p)}</p>`).join(''));
const sourceNote = (e) => e.source ? `<div class="source-note">Originally published on ${esc(e.source)}${e.date ? ` on ${prettyDate(e.date)}` : ''}. Preserved here as part of the Through My Quiet Lens archive.</div>` : '';
const tagHtml = (tags=[]) => `<div class="tags">${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`;

function nav(active='') {
  const items = [
    ['DC Decoded','/dc-decoded/','dc'],['Essays','/essays/','essays'],['Working Principles','/principles/','principles'],['Library','/library/','library'],['About','/about/','about'],['Subscribe','/subscribe/','subscribe']
  ];
  return `<header><div class="container nav"><a class="brand" href="/">Through My Quiet Lens</a><button class="menu-button" aria-label="Open menu" aria-expanded="false">Menu</button><nav class="nav-links" aria-label="Primary">${items.map(([label,url,key])=>`<a href="${url}"${active===key?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header>`;
}

function footer() {
  return `<footer><div class="container"><div class="footer-grid"><div><div class="footer-brand">Through My Quiet Lens</div><p>Thoughtful observations by ${esc(site.author)}.</p></div><div class="footer-links"><a href="/library/">Library</a><a href="/through-my-quiet-lens/">Quiet Lens</a><a href="/essays/">Essays</a><a href="/principles/">Principles</a><a href="/ucla-anderson/">UCLA Anderson</a><a href="/conversations/">Conversations</a><a href="/dc-decoded/">DC Decoded</a><a href="/projects/">Projects</a><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/subscribe/">Subscribe</a><a href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div><div class="copyright">© <span class="year"></span> ${esc(site.author)}. Built for reading, not scrolling.</div></div></footer>`;
}

function layout({title=site.title, description=site.description, body, active='', canonical='/'}) {
  const fullTitle = title === site.title ? title : `${title} — ${site.title}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.url}${canonical}"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${site.url}${canonical}"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip-link" href="#main">Skip to content</a><div class="site-shell">${nav(active)}<main id="main">${body}</main>${footer()}</div><script src="/site.js" defer></script></body></html>`;
}

function write(route, html) {
  const file = route.endsWith('.xml') || route.endsWith('.txt') ? path.join(out, route) : path.join(out, route, 'index.html');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
}

const findEssay = (slug) => essays.find(e=>e.slug===slug);
const startHere = [
  findEssay('gratitude'),
  findEssay('the-contract-is-the-beginning'),
  findEssay('finding-my-voice'),
  findEssay('ai-extend-my-thinking-or-avoid-it')
].filter(Boolean);
const homeLatest = essays.filter(e=>e.date).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,3);
const home = `<section class="home-hero"><div class="container home-hero-inner"><p class="eyebrow">An independent publication by Praveen Gangaraju</p><h1>Through My Quiet Lens</h1><p class="home-deck">Clear-eyed writing on data centres, infrastructure and AI, plus the reflections on leadership and life that shape how I think about them.</p><div class="home-actions"><a class="button" href="/dc-decoded/">Read DC Decoded →</a><a class="text-button" href="/essays/">Browse the essays →</a></div><p class="home-note">15+ years building infrastructure markets across Asia and the US. Writing to think clearly, in public.</p></div></section>
<section class="home-intro section"><div class="container home-intro-grid"><p class="eyebrow">Why I write</p><div><h2>I did not begin writing because I had answers.</h2><p class="home-intro-lead">I began because slowing down long enough to put thoughts into words often revealed questions I had not realised I was asking.</p><p>Some essays come from boardrooms. Others from classrooms, conversations, family, or ordinary moments that quietly changed how I think. This website is where I continue that conversation.</p></div></div></section>
<section class="section home-start" id="start-here"><div class="container"><div class="section-head"><div><p class="eyebrow">A considered beginning</p><h2>Start here</h2></div><p>Five entry points into the ideas, experiences and questions behind this publication.</p></div><div class="start-list">
<a class="start-item" href="/essays/gratitude/"><span class="start-no">01</span><div><span class="start-kicker">Where everything begins</span><h3>Gratitude</h3><p>A reflection on the people and sacrifices that quietly shape a life.</p></div><span class="start-arrow">→</span></a>
<a class="start-item" href="/principles/the-contract-is-the-beginning/"><span class="start-no">02</span><div><span class="start-kicker">How I think about trust</span><h3>The Contract Is the Beginning</h3><p>Why signing the agreement is only the start of the relationship.</p></div><span class="start-arrow">→</span></a>
<a class="start-item" href="/ucla-anderson/anderson-gave-me-a-village/"><span class="start-no">03</span><div><span class="start-kicker">Why community matters</span><h3>Anderson Gave Me a Village</h3><p>What an MBA taught me about belonging, contribution and shared journeys.</p></div><span class="start-arrow">→</span></a>
<a class="start-item" href="/projects/green-ai/"><span class="start-no">04</span><div><span class="start-kicker">Technology needs responsibility</span><h3>Green AI</h3><p>A practical experiment in reducing the computational waste of everyday AI use.</p></div><span class="start-arrow">→</span></a>
<a class="start-item" href="/essays/finding-my-voice/"><span class="start-no">05</span><div><span class="start-kicker">Why I write</span><h3>Finding My Voice</h3><p>Learning that a quiet voice does not have to be an invisible one.</p></div><span class="start-arrow">→</span></a>
</div></div></section>
<section class="section home-collections"><div class="container"><div class="section-head"><div><p class="eyebrow">The shelves</p><h2>Explore by collection</h2></div><a href="/library/">View the complete library →</a></div><div class="home-collection-list">
<a href="/through-my-quiet-lens/"><span>01</span><div><h3>Through My Quiet Lens</h3><p>Personal reflections on work, life, family and growth.</p></div><b>→</b></a>
<a href="/principles/"><span>02</span><div><h3>Working Principles</h3><p>Leadership, trust, negotiation and commercial judgement.</p></div><b>→</b></a>
<a href="/ucla-anderson/"><span>03</span><div><h3>UCLA Anderson</h3><p>Learning, curiosity, community and the people behind the degree.</p></div><b>→</b></a>
<a href="/dc-decoded/"><span>04</span><div><h3>DC Decoded</h3><p>Clear-eyed writing on data centres and critical infrastructure.</p></div><b>→</b></a>
<a href="/projects/green-ai/"><span>05</span><div><h3>Green AI</h3><p>Research and experiments for more sustainable use of technology.</p></div><b>→</b></a>
<a href="/projects/sage-for-ai/"><span>06</span><div><h3>SAGE for AI</h3><p>Better human–AI decisions through judgement, restraint and awareness.</p></div><b>→</b></a>
</div></div></section>
<section class="home-quote"><div class="reading"><blockquote>“Writing is not about having the answers. It is about slowing down enough to ask better questions.”</blockquote></div></section>
<section class="section home-latest"><div class="container"><div class="section-head"><div><p class="eyebrow">New on the shelf</p><h2>Latest writing</h2></div><a href="/library/">Browse all writing →</a></div><div class="cards">${homeLatest.map(e=>`<article class="card"><div class="meta"><span>${prettyDate(e.date)}</span><span>${e.readingTime}</span></div><h3><a href="/essays/${e.slug}/">${esc(e.displayTitle || e.title)}</a></h3><p>${esc(e.description)}</p><a class="read-link" href="/essays/${e.slug}/">Read the essay →</a></article>`).join('')}</div></div></section>
<section class="section home-about"><div class="container home-about-grid"><p class="eyebrow">Behind the lens</p><div><h2>Hi, I’m Praveen.</h2><p class="home-about-lead">Commercial leader. Lifelong learner. Occasional photographer. Always curious.</p><p>I have spent more than fifteen years building markets, relationships and infrastructure businesses across India, Singapore and the United States. Here, I write about the ideas behind that experience, and the quieter lessons that came from classrooms, conversations, family and life.</p><div class="home-about-links"><a href="/about/">Read my story →</a><a href="/contact/">Start a conversation →</a></div></div></div></section><section class="section home-thanks"><div class="container"><p class="home-thanks-text">Thank you for giving this piece your time. I believe it is the biggest gift anyone can give.</p></div></section>`;
write('', layout({body:home, canonical:'/'}));

const quietLens = essays.filter(e=>e.collection==='Through My Quiet Lens').sort((a,b)=>(a.collectionOrder||999)-(b.collectionOrder||999));
const quietLensList = `<section class="page-hero quiet-hero"><div class="container"><p class="eyebrow">A curated reading journey</p><h1 class="page-title">Through My Quiet Lens</h1><p class="page-lead">Personal stories about family, identity, resilience, culture and the quiet moments that shape how we see the world.</p><div class="journey-note"><strong>Begin at the beginning</strong><span>The essays are arranged for a reader to follow the journey, not by the date they were published.</span></div></div></section><section class="section"><div class="container journey-list">${quietLens.map((e,i)=>`<article class="journey-item"><div class="journey-number">${String(i+1).padStart(2,'0')}</div><div><div class="meta"><span>${e.readingTime}</span>${e.tags?.[0]?`<span>${esc(e.tags[0])}</span>`:''}</div><h2><a href="/essays/${e.slug}/">${esc(e.displayTitle || e.title)}</a></h2>${e.subtitle?`<p class="journey-subtitle">${esc(e.subtitle)}</p>`:''}<p>${esc(e.description)}</p></div><a class="journey-arrow" href="/essays/${e.slug}/" aria-label="Read ${esc(e.title)}">→</a></article>`).join('')}</div></section>`;
write('through-my-quiet-lens', layout({title:'Through My Quiet Lens', description:'A curated reading journey through Praveen Gangaraju’s personal essays.', body:quietLensList, active:'quiet-lens', canonical:'/through-my-quiet-lens/'}));

const libraryStart = [
  ['Gratitude','/essays/gratitude/','A reflection on the people and circumstances that quietly make a life possible.'],
  ['The Contract Is the Beginning','/principles/the-contract-is-the-beginning/','Why trust is built after the signature, not before it.'],
  ['Anderson Gave Me a Village','/ucla-anderson/anderson-gave-me-a-village/','What belonging can change in a demanding learning journey.'],
  ['$3 Trillion in Data Centers by 2030','/dc-decoded/3-trillion-in-data-centers-by-2030/','A starting point for understanding the infrastructure behind the AI economy.'],
  ['Am I Using AI to Extend My Thinking—or Avoid It?','/essays/ai-extend-my-thinking-or-avoid-it/','A question about convenience, struggle and human judgement.']
];
const libraryCollections = [
  ['Through My Quiet Lens','/through-my-quiet-lens/','Personal reflections on growth, family, belonging and the moments that change how we see.'],
  ['Working Principles','/principles/','Commercial and leadership beliefs shaped by customers, colleagues, classrooms and mistakes.'],
  ['UCLA Anderson','/ucla-anderson/','Learning, community and the experiences that made an MBA more than a degree.'],
  ['DC Decoded','/dc-decoded/','Data centres, power, digital infrastructure and the commercial systems behind technology.'],
  ['Green AI','/projects/green-ai/','A practical research experiment into lower-waste everyday AI use.'],
  ['SAGE for AI','/projects/sage-for-ai/','Thoughtful, sustainable and responsible human–AI engagement.']
];
const library = `<section class="page-hero library-hero"><div class="container"><p class="eyebrow">The complete body of work</p><h1 class="page-title">Library</h1><p class="page-lead">A curated home for essays, working principles, conversations and specialist writing. Begin with a reading path or browse by collection.</p></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Start here</p><h2>Five ways into the work</h2></div><p>These pieces offer the clearest introduction to the ideas that return throughout the publication.</p></div><div class="library-start">${libraryStart.map((x,i)=>`<a href="${x[1]}" class="library-start-item"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p></div><strong>Read →</strong></a>`).join('')}</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Collections</p><h2>Choose a lens</h2></div><p>Each collection follows a distinct question, but the same themes often cross between them.</p></div><div class="library-collections">${libraryCollections.map(x=>`<a class="library-collection" href="${x[1]}"><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p><span>Explore collection →</span></a>`).join('')}</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Everything</p><h2>Browse all writing</h2></div><p>${essays.length + principles.length + dc.length} published pieces across the main written collections.</p></div><div class="library-all">${[...essays.map(e=>({...e,url:`/essays/${e.slug}/`})),...principles.map(e=>({...e,collection:'Working Principles',url:`/principles/${e.slug}/`,description:e.text})),...dc.map(e=>({...e,collection:'DC Decoded',url:`/dc-decoded/${e.slug}/`}))].map(e=>`<article><div class="meta"><span>${esc(e.collection)}</span><span>${esc(e.readingTime||'2 min read')}</span></div><h3><a href="${e.url}">${esc(e.title)}</a></h3><p>${esc(e.description||'')}</p></article>`).join('')}</div></div></section>`;
write('library', layout({title:'Library', description:'The complete Through My Quiet Lens library.', body:library, active:'library', canonical:'/library/'}));

const standaloneEssays = essays.filter(e=>e.collection!=='Through My Quiet Lens');
const isShort = e => /^1 min/.test(e.readingTime||'');
const essaysList = `<section class="page-hero"><div class="container"><p class="eyebrow">Writing</p><h1 class="page-title">Essays</h1><p class="page-lead">Standalone essays and reflections. The sequential personal series now lives only under Quiet Lens.</p></div></section><section class="section"><div class="container list">${standaloneEssays.map(e=>`<article class="list-item${isShort(e)?' list-item-short':''}"><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div><div><h2><a href="/essays/${e.slug}/">${esc(e.title)}</a></h2><p>${esc(e.description)}</p>${tagHtml(e.tags)}</div><a href="/essays/${e.slug}/" aria-label="Read ${esc(e.title)}">Read →</a></article>`).join('')}</div></section>`;
write('essays', layout({title:'Essays', description:'Essays by Praveen Gangaraju.', body:essaysList, active:'essays', canonical:'/essays/'}));

for (const e of essays) {
  const sequence = e.collection==='Through My Quiet Lens' ? quietLens : essays; const idx = sequence.findIndex(x=>x.slug===e.slug); const related = [sequence[idx-1], sequence[idx+1]].filter(Boolean);
  const body = `<article><header class="article-head"><div class="reading"><p class="eyebrow">Essay</p><h1>${esc(e.displayTitle || e.title)}</h1>${e.subtitle ? `<p class="article-subtitle">${esc(e.subtitle)}</p>` : ``}<p class="deck">${esc(e.description)}</p><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div>${tagHtml(e.tags)}</div></header><div class="article reading">${articleBody(e)}${sourceNote(e)}<aside class="article-subscribe"><p class="eyebrow">Stay in touch</p><h2>Enjoyed this reflection?</h2><p>Receive future essays directly in your inbox.</p><a class="button" href="/subscribe/">Subscribe →</a></aside><div class="article-end"><strong>${e.collection==='Through My Quiet Lens' ? 'Continue the journey' : 'Continue exploring'}</strong>${related.map(r=>`<p><a href="/essays/${r.slug}/">${esc(r.title)} →</a></p>`).join('')}</div></div></article>`;
  write(`essays/${e.slug}`, layout({title:e.title, description:e.description, body, active:'essays', canonical:`/essays/${e.slug}/`}));
}

const pbody = `<section class="page-hero principles-hero"><div class="container"><p class="eyebrow">Ideas carried forward</p><h1 class="page-title">Working Principles</h1><p class="page-lead">Beliefs shaped by customers, colleagues, classrooms and mistakes. Not universal rules—simply ideas I try to return to.</p></div></section><section class="section"><div class="container principle-grid principle-library">${principles.map(p=>`<article class="principle principle-card"><div class="num">PRINCIPLE ${String(p.number).padStart(2,'0')}</div><h2><a href="/principles/${p.slug}/">${esc(p.title)}</a></h2><p>${esc(p.text)}</p><div class="meta"><span>${esc(p.readingTime || '2 min read')}</span><span>From LinkedIn</span></div><a class="read-link" href="/principles/${p.slug}/">Read the principle →</a></article>`).join('')}</div></section>`;
write('principles', layout({title:'Working Principles', description:'Working principles by Praveen Gangaraju.', body:pbody, active:'principles', canonical:'/principles/'}));

principles.forEach((p,i)=>{
  const prev=principles[i-1], next=principles[i+1];
  const navLinks = `<div class="article-journey">${prev?`<a href="/principles/${prev.slug}/"><span>Previous principle</span><strong>← ${esc(prev.title)}</strong></a>`:'<span></span>'}${next?`<a class="next" href="/principles/${next.slug}/"><span>Next principle</span><strong>${esc(next.title)} →</strong></a>`:'<span></span>'}</div>`;
  const body = `<article><section class="article-head principle-head"><div class="reading"><p class="eyebrow">Working Principle ${String(p.number).padStart(2,'0')}</p><h1>${esc(p.title)}</h1><p class="deck">${esc(p.text)}</p><div class="meta"><span>${esc(p.readingTime || '2 min read')}</span><span>Originally published on LinkedIn</span></div>${tagHtml(p.tags)}</div></section><section class="article-section"><div class="reading article-body">${p.bodyHtml}${sourceNote(p)}${navLinks}<p class="back-link"><a href="/principles/">← All Working Principles</a></p></div></section></article>`;
  write(`principles/${p.slug}`, layout({title:p.title, description:p.text, body, active:'principles', canonical:`/principles/${p.slug}/`}));
});

const five = conversations.find(c=>c.slug==='five-percent-conversations');
const celebrate = conversations.find(c=>c.slug==='celebrate-2026');
const cbody = `<section class="page-hero"><div class="container"><p class="eyebrow">Listening as a way of learning</p><h1 class="page-title">Conversations</h1><p class="page-lead">Two different projects, connected by one belief: people reveal far more when we make the time to listen.</p></div></section><section class="section"><div class="container conversation-grid"><article class="conversation-card"><p class="eyebrow">Personal podcast</p><h2>5% Conversations</h2><p>${esc(five.description)}</p><a class="read-link" href="/conversations/five-percent-conversations/">Read the story →</a></article><article class="conversation-card"><p class="eyebrow">UCLA Anderson</p><h2>Celebrate 2026</h2><p>${esc(celebrate.description)}</p><a class="read-link" href="/conversations/celebrate-2026/">Explore the project →</a></article></div></section>`;
write('conversations', layout({title:'Conversations', description:'5% Conversations and Celebrate 2026 by Praveen Gangaraju.', body:cbody, active:'conversations', canonical:'/conversations/'}));

const fiveBody = `<section class="page-hero"><div class="container"><p class="eyebrow">Personal podcast</p><h1 class="page-title">5% Conversations</h1><p class="page-lead">${esc(five.description)}</p></div></section><section class="section"><div class="reading conversation-story"><h2>Why I started it</h2><p>Early in my UCLA Anderson journey, I heard an idea that stayed with me: anyone who wants to do well in a profession must first understand what everyone else is doing, do those fundamentals well, and then bring the extra dedication, commitment and trust that can place them in the top five per cent.</p><p>I used that idea in a different way. I began reaching out to classmates and inviting them into conversations. Each one gave me a chance to learn something I did not know, while also developing a personal connection that might never have grown from a routine introduction.</p><p>That practice became <strong>5% Conversations</strong>.</p><p>It is not about claiming to belong to the top five per cent. It is about making the additional effort: asking one more question, listening more carefully, preparing with intention and treating trust as something worth earning.</p><p>Over time, I realised that conversations could do two things at once. They could expand what I knew and deepen how well I knew the person sitting across from me.</p><blockquote><p>The extra five per cent is often not a secret. It is the decision to show up with greater curiosity, commitment and care.</p></blockquote><p><a class="button external-button" href="${esc(five.spotify)}" target="_blank" rel="noopener noreferrer">Listen on Spotify ↗</a></p><p class="back-link"><a href="/conversations/">← Back to Conversations</a></p></div></section>`;
write('conversations/five-percent-conversations', layout({title:'5% Conversations', description:five.description, body:fiveBody, active:'conversations', canonical:'/conversations/five-percent-conversations/'}));

const celebrateBody = `<section class="page-hero"><div class="container"><p class="eyebrow">UCLA Anderson Executive MBA</p><h1 class="page-title">Celebrate 2026</h1><p class="page-lead">${esc(celebrate.description)}</p></div></section><section class="section"><div class="reading conversation-story"><h2>A community storytelling project</h2><p><strong>Celebrate 2026</strong> is separate from 5% Conversations. It was created for the UCLA Anderson Executive MBA community as part of the Drive Time podcast series.</p><p>The idea was simple: help classmates move beyond names, roles and résumés, and hear the experiences that shaped the people sharing the programme with them.</p><p>Hosting these conversations became one of the most meaningful parts of my Anderson journey. Each episode created space for a classmate to reflect on leadership, career, family, change and the path that brought them to UCLA.</p><p>The project now has its own website, while UCLA Anderson hosts the official Drive Time podcast page.</p><div class="link-stack"><a class="button external-button" href="${esc(celebrate.website)}" target="_blank" rel="noopener noreferrer">Visit the Celebrate 2026 website ↗</a><a class="text-button" href="${esc(celebrate.ucla)}" target="_blank" rel="noopener noreferrer">View the official UCLA Anderson page ↗</a></div><p class="back-link"><a href="/conversations/">← Back to Conversations</a></p></div></section>`;
write('conversations/celebrate-2026', layout({title:'Celebrate 2026', description:celebrate.description, body:celebrateBody, active:'conversations', canonical:'/conversations/celebrate-2026/'}));

const dcList = `<section class="page-hero"><div class="container"><p class="eyebrow">Infrastructure notes</p><h1 class="page-title">DC Decoded</h1><p class="page-lead">Clear-eyed observations on the systems, constraints and commercial choices behind digital infrastructure.</p></div></section><section class="section"><div class="container list">${dc.map(e=>`<article class="list-item${isShort(e)?' list-item-short':''}"><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div><div><h2><a href="/dc-decoded/${e.slug}/">${esc(e.title)}</a></h2><p>${esc(e.description)}</p></div><a href="/dc-decoded/${e.slug}/">Read →</a></article>`).join('')}</div></section>`;
write('dc-decoded', layout({title:'DC Decoded', description:'Data-centre and digital infrastructure writing by Praveen Gangaraju.', body:dcList, active:'dc', canonical:'/dc-decoded/'}));
for (const e of dc) {
  const body = `<article><header class="article-head"><div class="reading"><p class="eyebrow">DC Decoded</p><h1>${esc(e.title)}</h1><p class="deck">${esc(e.description)}</p><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div></div></header><div class="article reading">${articleBody(e)}${sourceNote(e)}<aside class="article-subscribe"><p class="eyebrow">Stay in touch</p><h2>Enjoyed this reflection?</h2><p>Receive future essays directly in your inbox.</p><a class="button" href="/subscribe/">Subscribe →</a></aside><div class="article-end"><a href="/dc-decoded/">Back to DC Decoded →</a></div></div></article>`;
  write(`dc-decoded/${e.slug}`, layout({title:e.title, description:e.description, body, active:'dc', canonical:`/dc-decoded/${e.slug}/`}));
}


const projects = `<section class="page-hero"><div class="container"><p class="eyebrow">Research & initiatives</p><h1 class="page-title">Projects</h1><p class="page-lead">Work that moves beyond reflection into experiments, tools and communities built around an idea.</p></div></section><section class="section"><div class="container project-grid"><article class="project-card"><p class="eyebrow">Research experiment</p><h2>Green AI</h2><p>Can a small change in how we prompt AI reduce unnecessary computation without reducing usefulness? This project began with a simple custom instruction and a small cross-model pilot.</p><a class="read-link" href="/projects/green-ai/">Explore Green AI →</a></article><article class="project-card"><p class="eyebrow">Public initiative</p><h2>SAGE for AI</h2><p>A developing initiative focused on more thoughtful, sustainable and responsible everyday use of artificial intelligence.</p><a class="read-link" href="/projects/sage-for-ai/">Explore SAGE for AI →</a></article></div></section>`;
write('projects', layout({title:'Projects', description:'Research and initiatives by Praveen Gangaraju.', body:projects, active:'projects', canonical:'/projects/'}));

const greenAI = `<section class="page-hero"><div class="container"><p class="eyebrow">Research experiment</p><h1 class="page-title">Green AI</h1><p class="page-lead">Testing whether a small behavioural intervention can reduce the computational waste hidden inside everyday AI use.</p></div></section><section class="section"><div class="reading project-story"><h2>The question</h2><p>Most conversations about AI sustainability focus on data centres, model architecture and energy supply. Those questions matter. But there is also a quieter question on the demand side: can ordinary users reduce unnecessary output through better defaults?</p><h2>The experiment</h2><p>The first pilot tested one short custom instruction designed to encourage concise, direct answers. Eleven participants used ChatGPT, Claude and Gemini without changing models or receiving prompt-engineering training.</p><div class="project-stat"><strong>About 65%</strong><span>average reduction in output tokens during the initial pilot</span></div><p>The early result is not a final scientific conclusion. It is a signal worth testing more carefully: small behavioural interventions may help reduce computational demand while preserving usefulness.</p><h2>What comes next</h2><p>The next stage expands the sample, improves measurement and tests whether the intervention remains useful across different tasks and user groups. The larger goal is to make sustainable AI use practical rather than abstract.</p><p class="back-link"><a href="/projects/">← Back to Projects</a></p></div></section>`;
write('projects/green-ai', layout({title:'Green AI', description:'A behavioural experiment exploring lower-waste everyday AI use.', body:greenAI, active:'projects', canonical:'/projects/green-ai/'}));

const sage = `<section class="page-hero"><div class="container"><p class="eyebrow">Public initiative</p><h1 class="page-title">SAGE for AI</h1><p class="page-lead">A developing platform for thoughtful, sustainable and responsible engagement with artificial intelligence.</p></div></section><section class="section"><div class="reading project-story"><h2>Why SAGE</h2><p>AI is becoming part of ordinary work and life faster than most people have had time to think about how they use it. SAGE begins from a simple belief: better technology use is not only about capability. It is also about judgement, restraint and awareness of impact.</p><h2>What it is becoming</h2><p>SAGE will translate research and complex sustainability questions into accessible habits, experiments and conversations. Green AI is one early research stream within that broader direction.</p><h2>Current stage</h2><p>The initiative is still being shaped. Its first phase focuses on building a clear evidence base, sharing practical guidance and developing a community interested in using AI with greater intention.</p><blockquote><p>Use intelligence wisely—both the machine’s and our own.</p></blockquote><p class="back-link"><a href="/projects/">← Back to Projects</a></p></div></section>`;
write('projects/sage-for-ai', layout({title:'SAGE for AI', description:'A developing initiative for sustainable and thoughtful AI use.', body:sage, active:'projects', canonical:'/projects/sage-for-ai/'}));

const contact = `<section class="page-hero"><div class="container"><p class="eyebrow">Contact</p><h1 class="page-title">Start a conversation</h1><p class="page-lead">For thoughtful responses, collaboration ideas, speaking enquiries or simply to say hello.</p></div></section><section class="section"><div class="reading contact-card"><h2>Email</h2><p><a class="contact-link" href="mailto:${esc(site.email)}">${esc(site.email)}</a></p><p>I'd love to hear from you. Whether it's a thoughtful conversation, a question, or simply to say hello, feel free to get in touch.</p><h2>LinkedIn</h2><p><a href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">Connect with Praveen on LinkedIn ↗</a></p><p class="quiet-note">I may not always respond immediately, but I read every genuine note.</p></div></section>`;
write('contact', layout({title:'Contact', description:'Contact Praveen Gangaraju.', body:contact, active:'contact', canonical:'/contact/'}));

const subscribeForm = `<form class="subscribe-form" action="https://buttondown.com/api/emails/embed-subscribe/${esc(site.buttondownUsername)}" method="post" target="popupwindow" onsubmit="window.open('https://buttondown.com/${esc(site.buttondownUsername)}', 'popupwindow')"><label for="bd-email">Email address</label><div class="subscribe-row"><input id="bd-email" name="email" type="email" autocomplete="email" placeholder="you@example.com" required><button class="button" type="submit">Subscribe</button></div><p class="form-note">Powered by Buttondown. Unsubscribe at any time.</p></form>`;
const subscribe = `<section class="page-hero"><div class="container"><p class="eyebrow">Subscribe</p><h1 class="page-title">Thoughtful writing, without the noise</h1><p class="page-lead">I write when there is something worth sharing—not because a calendar says I should.</p></div></section><section class="section"><div class="reading subscribe-card"><h2>Join the quiet list</h2><p>Receive new essays, project updates and DC Decoded articles directly in your inbox.</p>${subscribeForm}<p class="quiet-note">No pop-ups. No weekly obligation. Only something worth sharing.</p><p><a class="text-button" href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">Or follow on LinkedIn ↗</a></p></div></section>`;
write('subscribe', layout({title:'Subscribe', description:'Subscribe to new writing from Through My Quiet Lens.', body:subscribe, active:'subscribe', canonical:'/subscribe/'}));

const about = `<section class="page-hero"><div class="container"><p class="eyebrow">About</p><h1 class="page-title">The person behind the lens</h1><p class="page-lead">A little context for the experiences, people and places that shape the writing.</p></div></section><section class="section"><div class="container about-grid"><aside><p>Praveen Gangaraju<br>Singapore</p><p><a href="${esc(site.linkedin)}">LinkedIn →</a><br><a href="mailto:${esc(site.email)}">Email →</a></p></aside><div><section><h2>Why I write</h2><p>I do not write because I have all the answers. I write because the act of writing helps me understand an experience more clearly. Through My Quiet Lens is where those observations become essays, conversations and working principles.</p></section><section><h2>My journey</h2><p>I grew up in Chennai in a family of teachers and built my career across India, Singapore and the United States. Most of my professional life has been spent in commercial leadership, market development and mission-critical infrastructure. UCLA Anderson later gave me a new classroom—and a community that sharpened how I think about leadership, belonging and learning.</p></section><section><h2>Family</h2><p>My wife and daughter shape how I see success, responsibility and growth. They appear here only when a shared experience genuinely belongs in the story. This publication is personal, but it is not a public diary.</p></section><section><h2>Percy & Pluto</h2><p>I spent more than forty years without a dog. Then Percy and Pluto arrived and quietly changed how I think about patience, presence, routine, trust and home. They sometimes appear in the writing—not because this is a website about dogs, but because some of life’s most effective teachers have four legs.</p></section><section><h2>Professional background</h2><p>I have worked in commercial roles for more than fifteen years, building markets, customer relationships and infrastructure businesses across APAC and the United States. The detailed professional version lives on LinkedIn. This space is for the ideas behind the experience.</p></section></div></div></section>`;
write('about', layout({title:'About', description:'About Praveen Gangaraju and Through My Quiet Lens.', body:about, active:'about', canonical:'/about/'}));

const urls = ['', 'library/', 'essays/', ...essays.map(e=>`essays/${e.slug}/`), 'principles/', ...principles.map(p=>`principles/${p.slug}/`), 'conversations/', 'conversations/five-percent-conversations/', 'conversations/celebrate-2026/', 'dc-decoded/', ...dc.map(e=>`dc-decoded/${e.slug}/`), 'ucla-anderson/', 'ucla-anderson/anderson-gave-me-a-village/', 'ucla-anderson/the-biggest-lessons-werent-always-in-the-classroom/', 'ucla-anderson/the-most-unexpected-part-of-my-mba/', 'ucla-anderson/the-degree-was-the-destination/', 'ucla-anderson/six-hundred-photos-one-community/', 'ucla-anderson/ucla-x-lbs-lessons-friendships-stories-that-stay-with-us/', 'projects/', 'projects/green-ai/', 'projects/sage-for-ai/', 'about/', 'contact/', 'subscribe/'];
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.url}/${u}</loc></url>`).join('')}</urlset>`);
write('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
write('404', layout({title:'Page not found', description:'This page could not be found.', body:`<section class="page-hero"><div class="reading"><p class="eyebrow">404</p><h1 class="page-title">This path ends here.</h1><p class="page-lead">The idea may have moved, or the link may be incomplete.</p><p><a class="button" href="/">Return home →</a></p></div></section>`, canonical:'/404/'}));

console.log(`Built ${urls.length + 4} files in ${out}`);
