import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const contentDir = path.join(root, 'content');
const publicDir = path.join(root, 'public');
const readJson = (name) => JSON.parse(fs.readFileSync(path.join(contentDir, name), 'utf8'));
const site = readJson('site.json');
const essays = readJson('essays.json');
const principles = readJson('principles.json');
const conversations = readJson('conversations.json');
const dc = readJson('dcdecoded.json');

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
fs.cpSync(publicDir, out, { recursive: true });

const esc = (s='') => String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const prettyDate = (d) => d ? new Intl.DateTimeFormat('en-GB', { day:'numeric', month:'long', year:'numeric' }).format(new Date(`${d}T12:00:00Z`)) : '';
const dateHtml = (e) => e.date ? `<span>${prettyDate(e.date)}</span>` : (e.source ? `<span>Originally published on ${esc(e.source)}</span>` : '');
const articleBody = (e) => e.bodyHtml || (e.body || []).map(p=>`<p>${esc(p)}</p>`).join('');
const sourceNote = (e) => e.source ? `<div class="source-note">Originally published on ${esc(e.source)}. Republished here as part of the Through My Quiet Lens archive.</div>` : '';
const tagHtml = (tags=[]) => `<div class="tags">${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`;

function nav(active='') {
  const items = [
    ['Essays','/essays/','essays'],['Working Principles','/principles/','principles'],['Conversations','/conversations/','conversations'],['DC Decoded','/dc-decoded/','dc'],['Projects','/projects/','projects'],['About','/about/','about'],['Contact','/contact/','contact'],['Subscribe','/subscribe/','subscribe']
  ];
  return `<header><div class="container nav"><a class="brand" href="/">Through My Quiet Lens</a><button class="menu-button" aria-label="Open menu" aria-expanded="false">Menu</button><nav class="nav-links" aria-label="Primary">${items.map(([label,url,key])=>`<a href="${url}"${active===key?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header>`;
}

function footer() {
  return `<footer><div class="container"><div class="footer-grid"><div><div class="footer-brand">Through My Quiet Lens</div><p>Thoughtful observations by ${esc(site.author)}.</p></div><div class="footer-links"><a href="/essays/">Essays</a><a href="/principles/">Principles</a><a href="/conversations/">Conversations</a><a href="/dc-decoded/">DC Decoded</a><a href="/projects/">Projects</a><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/subscribe/">Subscribe</a><a href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div><div class="copyright">© <span class="year"></span> ${esc(site.author)}. Built for reading, not scrolling.</div></div></footer>`;
}

function layout({title=site.title, description=site.description, body, active='', canonical='/'}) {
  const fullTitle = title === site.title ? title : `${title} — ${site.title}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.url}${canonical}"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${site.url}${canonical}"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip-link" href="#main">Skip to content</a><div class="site-shell">${nav(active)}<main id="main">${body}</main>${footer()}</div><script src="/site.js" defer></script></body></html>`;
}

function write(route, html) {
  const file = route.endsWith('.xml') || route.endsWith('.txt') ? path.join(out, route) : path.join(out, route, 'index.html');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
}

const featured = essays.find(x=>x.featured) || essays[0];
const recent = essays.filter(x=>x.slug!==featured.slug).slice(0,3);
const home = `<section class="hero"><div class="container"><p class="eyebrow">An independent publication</p><h1>Through My Quiet Lens</h1><p class="welcome">Thank you for choosing to pause and explore.</p><p class="intro">Some ideas reveal themselves quickly. Others take time, quiet observation, and a willingness to look again. This is a place for the second kind.</p><p class="sub">A collection of essays, conversations and reflections on work, leadership, technology and everyday life.</p><a class="button" href="/essays/${featured.slug}/">Start reading <span aria-hidden="true">→</span></a></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Featured essay</p><h2>Begin here</h2></div><p>A considered starting point for understanding the ideas that shape this publication.</p></div><article class="featured"><div><div class="meta">${dateHtml(featured)}<span>${featured.readingTime}</span></div><h3><a href="/essays/${featured.slug}/">${esc(featured.title)}</a></h3></div><div><p>${esc(featured.description)}</p>${tagHtml(featured.tags)}<p><a class="read-link" href="/essays/${featured.slug}/">Read the essay →</a></p></div></article></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Recent writing</p><h2>Ideas in progress</h2></div><a href="/essays/">View all essays →</a></div><div class="cards">${recent.map(e=>`<article class="card"><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div><h3><a href="/essays/${e.slug}/">${esc(e.title)}</a></h3><p>${esc(e.description)}</p><a class="read-link" href="/essays/${e.slug}/">Continue reading →</a></article>`).join('')}</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Explore</p><h2>Five ways into the work</h2></div><p>Follow the kind of thinking that interests you rather than the date it was published.</p></div><div class="collections"><a class="collection" href="/essays/"><h3>Essays</h3><p>Longer reflections on work, leadership, relationships, technology and everyday life.</p></a><a class="collection" href="/principles/"><h3>Working Principles</h3><p>Ideas distilled from experience and expressed simply enough to carry forward.</p></a><a class="collection" href="/conversations/"><h3>Conversations</h3><p>Two distinct projects built around listening: a personal podcast and a UCLA Anderson community series.</p></a><a class="collection" href="/dc-decoded/"><h3>DC Decoded</h3><p>A specialist lens on data centres, digital infrastructure, power and the systems behind technology.</p></a><a class="collection" href="/projects/"><h3>Projects</h3><p>Research and initiatives translating reflection into practical experiments and shared learning.</p></a></div></div></section>
<section class="section"><div class="container about-grid"><aside><p class="eyebrow">About the author</p><p>Commercial leader, reflective writer, podcast host and lifelong student.</p></aside><div><h2>Hi, I’m Praveen.</h2><p>I write because writing helps me understand. Over the years I have worked across India, Singapore and the United States in commercial leadership and mission-critical infrastructure. The ideas that stay with me, however, often come from quieter moments—conversations, negotiations, classrooms, family and everyday experiences.</p><p><a href="/about/">More about this publication and the person behind it →</a></p></div></div></section>`;
write('', layout({body:home, canonical:'/'}));

const essaysList = `<section class="page-hero"><div class="container"><p class="eyebrow">Writing</p><h1 class="page-title">Essays</h1><p class="page-lead">Stories and reflections that explore an idea rather than rush towards a conclusion.</p></div></section><section class="section"><div class="container list">${essays.map(e=>`<article class="list-item"><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div><div><h2><a href="/essays/${e.slug}/">${esc(e.title)}</a></h2><p>${esc(e.description)}</p>${tagHtml(e.tags)}</div><a href="/essays/${e.slug}/" aria-label="Read ${esc(e.title)}">Read →</a></article>`).join('')}</div></section>`;
write('essays', layout({title:'Essays', description:'Essays by Praveen Gangaraju.', body:essaysList, active:'essays', canonical:'/essays/'}));

for (const e of essays) {
  const related = essays.filter(x=>x.slug!==e.slug).slice(0,2);
  const body = `<article><header class="article-head"><div class="reading"><p class="eyebrow">Essay</p><h1>${esc(e.displayTitle || e.title)}</h1>${e.subtitle ? `<p class="article-subtitle">${esc(e.subtitle)}</p>` : ``}<p class="deck">${esc(e.description)}</p><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div>${tagHtml(e.tags)}</div></header><div class="article reading">${articleBody(e)}${sourceNote(e)}<aside class="article-subscribe"><p class="eyebrow">Stay in touch</p><h2>Enjoyed this reflection?</h2><p>Receive future essays directly in your inbox.</p><a class="button" href="/subscribe/">Subscribe →</a></aside><div class="article-end"><strong>Continue exploring</strong>${related.map(r=>`<p><a href="/essays/${r.slug}/">${esc(r.title)} →</a></p>`).join('')}</div></div></article>`;
  write(`essays/${e.slug}`, layout({title:e.title, description:e.description, body, active:'essays', canonical:`/essays/${e.slug}/`}));
}

const pbody = `<section class="page-hero"><div class="container"><p class="eyebrow">A growing collection</p><h1 class="page-title">Working Principles</h1><p class="page-lead">Ideas shaped by experience. Not rules for everyone—simply principles I try to return to.</p></div></section><section class="section"><div class="container principle-grid">${principles.map(p=>`<article class="principle"><div class="num">PRINCIPLE ${String(p.number).padStart(2,'0')}</div><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p></article>`).join('')}</div></section>`;
write('principles', layout({title:'Working Principles', description:'Working principles by Praveen Gangaraju.', body:pbody, active:'principles', canonical:'/principles/'}));

const five = conversations.find(c=>c.slug==='five-percent-conversations');
const celebrate = conversations.find(c=>c.slug==='celebrate-2026');
const cbody = `<section class="page-hero"><div class="container"><p class="eyebrow">Listening as a way of learning</p><h1 class="page-title">Conversations</h1><p class="page-lead">Two different projects, connected by one belief: people reveal far more when we make the time to listen.</p></div></section><section class="section"><div class="container conversation-grid"><article class="conversation-card"><p class="eyebrow">Personal podcast</p><h2>5% Conversations</h2><p>${esc(five.description)}</p><a class="read-link" href="/conversations/five-percent-conversations/">Read the story →</a></article><article class="conversation-card"><p class="eyebrow">UCLA Anderson</p><h2>Celebrate 2026</h2><p>${esc(celebrate.description)}</p><a class="read-link" href="/conversations/celebrate-2026/">Explore the project →</a></article></div></section>`;
write('conversations', layout({title:'Conversations', description:'5% Conversations and Celebrate 2026 by Praveen Gangaraju.', body:cbody, active:'conversations', canonical:'/conversations/'}));

const fiveBody = `<section class="page-hero"><div class="container"><p class="eyebrow">Personal podcast</p><h1 class="page-title">5% Conversations</h1><p class="page-lead">${esc(five.description)}</p></div></section><section class="section"><div class="reading conversation-story"><h2>Why I started it</h2><p>Early in my UCLA Anderson journey, I heard an idea that stayed with me: anyone who wants to do well in a profession must first understand what everyone else is doing, do those fundamentals well, and then bring the extra dedication, commitment and trust that can place them in the top five per cent.</p><p>I used that idea in a different way. I began reaching out to classmates and inviting them into conversations. Each one gave me a chance to learn something I did not know, while also developing a personal connection that might never have grown from a routine introduction.</p><p>That practice became <strong>5% Conversations</strong>.</p><p>It is not about claiming to belong to the top five per cent. It is about making the additional effort: asking one more question, listening more carefully, preparing with intention and treating trust as something worth earning.</p><p>Over time, I realised that conversations could do two things at once. They could expand what I knew and deepen how well I knew the person sitting across from me.</p><blockquote><p>The extra five per cent is often not a secret. It is the decision to show up with greater curiosity, commitment and care.</p></blockquote><p><a class="button external-button" href="${esc(five.spotify)}" target="_blank" rel="noopener noreferrer">Listen on Spotify ↗</a></p><p class="back-link"><a href="/conversations/">← Back to Conversations</a></p></div></section>`;
write('conversations/five-percent-conversations', layout({title:'5% Conversations', description:five.description, body:fiveBody, active:'conversations', canonical:'/conversations/five-percent-conversations/'}));

const celebrateBody = `<section class="page-hero"><div class="container"><p class="eyebrow">UCLA Anderson Executive MBA</p><h1 class="page-title">Celebrate 2026</h1><p class="page-lead">${esc(celebrate.description)}</p></div></section><section class="section"><div class="reading conversation-story"><h2>A community storytelling project</h2><p><strong>Celebrate 2026</strong> is separate from 5% Conversations. It was created for the UCLA Anderson Executive MBA community as part of the Drive Time podcast series.</p><p>The idea was simple: help classmates move beyond names, roles and résumés, and hear the experiences that shaped the people sharing the programme with them.</p><p>Hosting these conversations became one of the most meaningful parts of my Anderson journey. Each episode created space for a classmate to reflect on leadership, career, family, change and the path that brought them to UCLA.</p><p>The project now has its own website, while UCLA Anderson hosts the official Drive Time podcast page.</p><div class="link-stack"><a class="button external-button" href="${esc(celebrate.website)}" target="_blank" rel="noopener noreferrer">Visit the Celebrate 2026 website ↗</a><a class="text-button" href="${esc(celebrate.ucla)}" target="_blank" rel="noopener noreferrer">View the official UCLA Anderson page ↗</a></div><p class="back-link"><a href="/conversations/">← Back to Conversations</a></p></div></section>`;
write('conversations/celebrate-2026', layout({title:'Celebrate 2026', description:celebrate.description, body:celebrateBody, active:'conversations', canonical:'/conversations/celebrate-2026/'}));

const dcList = `<section class="page-hero"><div class="container"><p class="eyebrow">Infrastructure notes</p><h1 class="page-title">DC Decoded</h1><p class="page-lead">Clear-eyed observations on the systems, constraints and commercial choices behind digital infrastructure.</p></div></section><section class="section"><div class="container list">${dc.map(e=>`<article class="list-item"><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div><div><h2><a href="/dc-decoded/${e.slug}/">${esc(e.title)}</a></h2><p>${esc(e.description)}</p></div><a href="/dc-decoded/${e.slug}/">Read →</a></article>`).join('')}</div></section>`;
write('dc-decoded', layout({title:'DC Decoded', description:'Data-centre and digital infrastructure writing by Praveen Gangaraju.', body:dcList, active:'dc', canonical:'/dc-decoded/'}));
for (const e of dc) {
  const body = `<article><header class="article-head"><div class="reading"><p class="eyebrow">DC Decoded</p><h1>${esc(e.title)}</h1><p class="deck">${esc(e.description)}</p><div class="meta">${dateHtml(e)}<span>${e.readingTime}</span></div></div></header><div class="article reading">${articleBody(e)}${sourceNote(e)}<aside class="article-subscribe"><p class="eyebrow">Stay in touch</p><h2>Enjoyed this reflection?</h2><p>Receive future essays directly in your inbox.</p><a class="button" href="/subscribe/">Subscribe →</a></aside><div class="article-end"><a href="/dc-decoded/">Back to DC Decoded →</a></div></div></article>`;
  write(`dc-decoded/${e.slug}`, layout({title:e.title, description:e.description, body, active:'dc', canonical:`/dc-decoded/${e.slug}/`}));
}


const projects = `<section class="page-hero"><div class="container"><p class="eyebrow">Research & initiatives</p><h1 class="page-title">Projects</h1><p class="page-lead">Work that moves beyond reflection into experiments, tools and communities built around an idea.</p></div></section><section class="section"><div class="container project-grid"><article class="project-card"><p class="eyebrow">Research experiment</p><h2>Green AI</h2><p>Can a small change in how we prompt AI reduce unnecessary computation without reducing usefulness? This project began with a simple custom instruction and a small cross-model pilot.</p><a class="read-link" href="/projects/green-ai/">Explore Green AI →</a></article><article class="project-card"><p class="eyebrow">Public initiative</p><h2>SAGE for AI</h2><p>A developing initiative focused on more thoughtful, sustainable and responsible everyday use of artificial intelligence.</p><a class="read-link" href="/projects/sage-for-ai/">Explore SAGE for AI →</a></article></div></section>`;
write('projects', layout({title:'Projects', description:'Research and initiatives by Praveen Gangaraju.', body:projects, active:'projects', canonical:'/projects/'}));

const greenAI = `<section class="page-hero"><div class="container"><p class="eyebrow">Research experiment</p><h1 class="page-title">Green AI</h1><p class="page-lead">Testing whether a small behavioural intervention can reduce the computational waste hidden inside everyday AI use.</p></div></section><section class="section"><div class="reading project-story"><h2>The question</h2><p>Most conversations about AI sustainability focus on data centres, model architecture and energy supply. Those questions matter. But there is also a quieter question on the demand side: can ordinary users reduce unnecessary output through better defaults?</p><h2>The experiment</h2><p>The first pilot tested one short custom instruction designed to encourage concise, direct answers. Eleven participants used ChatGPT, Claude and Gemini without changing models or receiving prompt-engineering training.</p><div class="project-stat"><strong>About 65%</strong><span>average reduction in output tokens during the initial pilot</span></div><p>The early result is not a final scientific conclusion. It is a signal worth testing more carefully: small behavioural interventions may help reduce computational demand while preserving usefulness.</p><h2>What comes next</h2><p>The next stage expands the sample, improves measurement and tests whether the intervention remains useful across different tasks and user groups. The larger goal is to make sustainable AI use practical rather than abstract.</p><p class="back-link"><a href="/projects/">← Back to Projects</a></p></div></section>`;
write('projects/green-ai', layout({title:'Green AI', description:'A behavioural experiment exploring lower-waste everyday AI use.', body:greenAI, active:'projects', canonical:'/projects/green-ai/'}));

const sage = `<section class="page-hero"><div class="container"><p class="eyebrow">Public initiative</p><h1 class="page-title">SAGE for AI</h1><p class="page-lead">A developing platform for thoughtful, sustainable and responsible engagement with artificial intelligence.</p></div></section><section class="section"><div class="reading project-story"><h2>Why SAGE</h2><p>AI is becoming part of ordinary work and life faster than most people have had time to think about how they use it. SAGE begins from a simple belief: better technology use is not only about capability. It is also about judgement, restraint and awareness of impact.</p><h2>What it is becoming</h2><p>SAGE will translate research and complex sustainability questions into accessible habits, experiments and conversations. Green AI is one early research stream within that broader direction.</p><h2>Current stage</h2><p>The initiative is still being shaped. Its first phase focuses on building a clear evidence base, sharing practical guidance and developing a community interested in using AI with greater intention.</p><blockquote><p>Use intelligence wisely—both the machine’s and our own.</p></blockquote><p class="back-link"><a href="/projects/">← Back to Projects</a></p></div></section>`;
write('projects/sage-for-ai', layout({title:'SAGE for AI', description:'A developing initiative for sustainable and thoughtful AI use.', body:sage, active:'projects', canonical:'/projects/sage-for-ai/'}));

const contact = `<section class="page-hero"><div class="container"><p class="eyebrow">Contact</p><h1 class="page-title">Start a conversation</h1><p class="page-lead">For thoughtful responses, collaboration ideas, speaking enquiries or simply to say hello.</p></div></section><section class="section"><div class="reading contact-card"><h2>Email</h2><p><a class="contact-link" href="mailto:${esc(site.email)}">${esc(site.email)}</a></p><p>I'd love to hear from you. Whether it's a thoughtful conversation, a question, or simply to say hello, feel free to get in touch.</p><h2>LinkedIn</h2><p><a href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">Connect with Praveen on LinkedIn ↗</a></p><p class="quiet-note">I may not always respond immediately, but I read every genuine note.</p></div></section>`;
write('contact', layout({title:'Contact', description:'Contact Praveen Gangaraju.', body:contact, active:'contact', canonical:'/contact/'}));

const subscribeForm = `<form class="subscribe-form" action="https://buttondown.com/api/emails/embed-subscribe/${esc(site.buttondownUsername)}" method="post" target="popupwindow" onsubmit="window.open('https://buttondown.com/${esc(site.buttondownUsername)}', 'popupwindow')"><label for="bd-email">Email address</label><div class="subscribe-row"><input id="bd-email" name="email" type="email" autocomplete="email" placeholder="you@example.com" required><button class="button" type="submit">Subscribe</button></div><p class="form-note">Powered by Buttondown. Unsubscribe at any time.</p></form>`;
const subscribe = `<section class="page-hero"><div class="container"><p class="eyebrow">Subscribe</p><h1 class="page-title">Thoughtful writing, without the noise</h1><p class="page-lead">I write when there is something worth sharing—not because a calendar says I should.</p></div></section><section class="section"><div class="reading subscribe-card"><h2>Join the quiet list</h2><p>Receive new essays, project updates and DC Decoded articles directly in your inbox.</p>${subscribeForm}<p class="quiet-note">No pop-ups. No weekly obligation. Only something worth sharing.</p><p><a class="text-button" href="${esc(site.linkedin)}" target="_blank" rel="noopener noreferrer">Or follow on LinkedIn ↗</a></p></div></section>`;
write('subscribe', layout({title:'Subscribe', description:'Subscribe to new writing from Through My Quiet Lens.', body:subscribe, active:'subscribe', canonical:'/subscribe/'}));

const about = `<section class="page-hero"><div class="container"><p class="eyebrow">About</p><h1 class="page-title">The person behind the lens</h1><p class="page-lead">A little context for the experiences, people and places that shape the writing.</p></div></section><section class="section"><div class="container about-grid"><aside><p>Praveen Gangaraju<br>Singapore</p><p><a href="${esc(site.linkedin)}">LinkedIn →</a><br><a href="mailto:${esc(site.email)}">Email →</a></p></aside><div><section><h2>Why I write</h2><p>I do not write because I have all the answers. I write because the act of writing helps me understand an experience more clearly. Through My Quiet Lens is where those observations become essays, conversations and working principles.</p></section><section><h2>My journey</h2><p>I grew up in Chennai in a family of teachers and built my career across India, Singapore and the United States. Most of my professional life has been spent in commercial leadership, market development and mission-critical infrastructure. UCLA Anderson later gave me a new classroom—and a community that sharpened how I think about leadership, belonging and learning.</p></section><section><h2>Family</h2><p>My wife and daughter shape how I see success, responsibility and growth. They appear here only when a shared experience genuinely belongs in the story. This publication is personal, but it is not a public diary.</p></section><section><h2>Percy & Pluto</h2><p>I spent more than forty years without a dog. Then Percy and Pluto arrived and quietly changed how I think about patience, presence, routine, trust and home. They sometimes appear in the writing—not because this is a website about dogs, but because some of life’s most effective teachers have four legs.</p></section><section><h2>Professional background</h2><p>I have worked in commercial roles for more than fifteen years, building markets, customer relationships and infrastructure businesses across APAC and the United States. The detailed professional version lives on LinkedIn. This space is for the ideas behind the experience.</p></section></div></div></section>`;
write('about', layout({title:'About', description:'About Praveen Gangaraju and Through My Quiet Lens.', body:about, active:'about', canonical:'/about/'}));

const urls = ['', 'essays/', ...essays.map(e=>`essays/${e.slug}/`), 'principles/', 'conversations/', 'conversations/five-percent-conversations/', 'conversations/celebrate-2026/', 'dc-decoded/', ...dc.map(e=>`dc-decoded/${e.slug}/`), 'projects/', 'projects/green-ai/', 'projects/sage-for-ai/', 'about/', 'contact/', 'subscribe/'];
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.url}/${u}</loc></url>`).join('')}</urlset>`);
write('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
write('404', layout({title:'Page not found', description:'This page could not be found.', body:`<section class="page-hero"><div class="reading"><p class="eyebrow">404</p><h1 class="page-title">This path ends here.</h1><p class="page-lead">The idea may have moved, or the link may be incomplete.</p><p><a class="button" href="/">Return home →</a></p></div></section>`, canonical:'/404/'}));

console.log(`Built ${urls.length + 4} files in ${out}`);
